### ISSUE TITLE
French Translations: Combine PMA API & Google Translate API

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#107]
## Description
Currently, Datalab can only be translated between English and French using hand-crafted translations pulled from the PMA API.

### 1. Utilize a translation service API
Implement translation through a translation service API, like Google Translate. PMA2020.org itself already does this.

<img width="1102" alt="screen shot 2018-07-30 at 9 24 08 am" src="https://user-images.githubusercontent.com/13045020/43400039-a1636042-93da-11e8-934b-3f46e41cf638.png">
<img width="1042" alt="screen shot 2018-07-30 at 9 24 19 am" src="https://user-images.githubusercontent.com/13045020/43400041-a2350f98-93da-11e8-9b09-9bec5ee7e581.png">

### 2. For French, utilize PMA API translations
Make sure that when the user selects "French" from the service API language selector menu, we also use the PMA API provided translations. Perhaps a good strategy is to wait for the UI translation in French to finish. Then after that event is finished, we can replace that text with French text from the PMA API.

Or, we could perhaps use the PMA API translations first, and then use the translation service API.

### 3. Update the existing language selector menu
Datalab already has a language selector menu that is different from the earlier screenshots shown from PMA2020.org.

<img width="299" alt="screen shot 2018-07-30 at 9 30 48 am" src="https://user-images.githubusercontent.com/13045020/43400263-42f4725c-93db-11e8-9307-2cd357710aa1.png">

We have some options to think about:
1. Add the new translation widget to the top of the page (like in the first screenshots). Then, add all of those languages into the existing language selector. Then, make it so that both widgets have the same behavior.
2. Add the new translation widget to the top of the page, but remove the old translation selector from the "Controls" widget / component.
3. Instead of adding a new widget, change it so that the current translation selector in the "Controls" widget / component calls the translation service API directly.

I think that maybe (2) is easiest, but (3) is best. Maybe we can implement (2) first, and then implement (3) later. @Bciar Does this seem OK to you?

### 4. Remove other languages; leave only English and French
I spoke with my team. They decided they only want English and French now. Sorry.

### 5. Combine Google Translate API French translations with PMA API French translations
I was trying to explain this in task (2), but I did not communicate good. Basically, we want to use PMA API translations if they are available. If they are not available, we want to translate using the Google Translate API.

Currently, we are using the PMA API to translate the "Controls", "Definitions", and "Styles" (maybe) widgets. We want to continue using PMA API translations for that.

So, Google Translate API should translate these other things on the page:

![all text](https://user-images.githubusercontent.com/13045020/44095442-d2e138c4-9fa6-11e8-8a55-436ce61ba8b0.png)

## Task List
- [x] 1. Utilize a translation service API
- [x] 2. For French, utilize PMA API translations
- [x] 3. Update the existing language selector menu
- [x] 4. Remove other languages; leave only English and French
- [x] 5. Combine Google Translate API French translations with PMA API French translations

**Comment by joeflack4** [comment]
@bciar Hey. I'm loving this! Thanks.

Just one bug I found. If you are in French, but click "chart", it goes back to English.

1. Before clicking chart
![1](https://user-images.githubusercontent.com/13045020/44270835-8e8e6400-a206-11e8-8c45-92b824ed8071.png)

2. After clicking chart
![2](https://user-images.githubusercontent.com/13045020/44270849-951cdb80-a206-11e8-91d5-d82dfbe7caaf.png)

**Comment by joeflack4** [comment]
@bciar Looks good!
