### ISSUE TITLE
On-hover Tooltips

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#37]
We would like some tooltips for various buttons in the widget on the left of the layout.

Later on, we are interested in having special "guided help" tooltips--please see https://www.statcompiler.com/en/# and click "guided help" to see what I mean. But right now, we are going to add some simple on-hover tooltips.

I think we use both notify js and bootstrap in Datalab? Feel free to use either of these for creating tooltips, or use whatever you think is best.

#### 1) Over-time 
>To chart data overtime, select multiple rounds of data from the same country.

#### 2) Chart
When enabled
_No tool tip._

When disabled<sup> (1)</sup>
> You must select Country-Rounds of data, an indicator, an option to break the data down, and a chart type in order to generate a chart.

#### 3) Pie Chart
> Pie charts are available to graph indicators that present data on various parts or portions that make up a whole. For example, method mix, which shows the portion of contraceptive users by each method type, may be graphed with a pie chart.

#### 4) Wealth tertile and quintile characteristics
When enabled
_No tool tip._

When disabled<sup> (i)</sup>
> Burkina Faso and Niger indicators may be broken down by wealth tertile; all other countries may be broken down by wealth quintile. Please adjust your country selections.

![screen shot 2018-02-02 at 11 12 39 am](https://user-images.githubusercontent.com/13045020/35742997-36a00f0a-080a-11e8-89a3-a6d310eb0a31.png)

### Footnotes
i. Currently when disabled, instead of a tooltip, the mouse pointer changes to a "cancellation / prohibited / no" symbol, like [this](https://cdn-enterprise.discourse.org/mcneel/uploads/default/original/3X/2/3/234e88ad13c8d9b16d8cbf53f6941cbe12781e73.png). When adding a tooltip to something that is disabled, feel free to remove this change in the mouse cursor. Or, keep it--whatever you think is best design.

### Task Summary
- [x] 1) Over-time tooltip
- [x] 2) Chart tooltip 
- [x] 3) Pie chart tooltip
- [x] 4) Wealth tertile and quintile characteristics tooltips

**Comment by joeflack4** [comment]
@jkpr Tested on local and looks great to me.
@bciar Thanks for the good work!
