### ISSUE TITLE
Styles Tab changes

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#42]
## Description
We want to make some changes to the *Styles* tab.

### 1) Axis labels & colors
Right now they are the opposite. Please look at image to see how it should be.
![axises](https://user-images.githubusercontent.com/13045020/39308025-6c5531d4-4932-11e8-9dca-59c559717b4b.png)

#### Current issue
If you change the title and axis labels, but then erase them, the title and axis labels do not appear on the chart. The title and axis labels do not return to their default values. Actually, we think that may be this is a good thing. It is possible that a user does not want any titles or axis labels.

But the problem is, if the user makes a title and axis label, it is possible the user may want to go back to the default value. But there is no way to know the default value without clicking "reset chart". And maybe the user does not want to click "reset chart".

![1](https://user-images.githubusercontent.com/13045020/39309160-54a50444-4935-11e8-887c-1670eb202b6f.png)
![2](https://user-images.githubusercontent.com/13045020/39309161-54b15eec-4935-11e8-90ca-00ee263bead0.png)
![3](https://user-images.githubusercontent.com/13045020/39309162-54c03c50-4935-11e8-9b63-2593476fd238.png)

#### What we want
We want a default value and placeholder on the title and axis labels.

Default value should be like this:
![default value](https://user-images.githubusercontent.com/13045020/39309628-7e149d98-4936-11e8-8d24-07a21b1c741b.png)
Placeholders should be like this:
![placeholders](https://user-images.githubusercontent.com/13045020/39309818-e3aad2e4-4936-11e8-9006-2c128e86f4fd.png)

### 3) Remove the "update chart" button
Remove this button. It is no longer useful. @Bciar You made a better way!

### 4) Reset Chart button - remove alert
When you click "reset chart", an alert appears. We should remove it.
![alert](https://user-images.githubusercontent.com/13045020/39310629-e49433e2-4938-11e8-93fc-6f6c21a97dde.png)

### 5) Reset Chart --> Reset Styles
Please rename this button to say "Reset Styles".

### 6) Reset Chart - No page refresh
Please remove page refresh when clicking this button. It is a better user experience with no page refresh. When we click "Reset Styles", it should do two things:
- Set all fields to default values
- Re-render the chart with default values

## Task Checklist
- [x] 1) Axis labels & colors
- [x] 2) Title & axis labels - Placeholders & default values
- [x] 3) Remove "update chart" button
- [x] 4) Reset Chart button - remove alert
- [x] 5) Reset Chart --> Reset Styles
- [x] 6) Reset Chart - No page refresh

**Comment by joeflack4** [comment]
@bciar Great job!
