### ISSUE TITLE
Guided Tour

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#50]
## Description
This is a new feature. Basically, we want something that helps users understand the basic UI of datalab. We are currently working on what text to display, but we want you to code the tour.

We are inspired a little by DHS's "STATcompiler" web app. They have a "guided help" button. When you select it, it adds [special tooltips](https://drive.google.com/drive/u/0/folders/1pmXGmZ3r09XuIf7pYivsyzZZXBcbg2SY). This is basically what we want. Take a look at it: https://www.statcompiler.com/en/

You are free to use whatever solution you think is best. If you are looking for a library to use, personally I am impressed by driver.js (https://github.com/kamranahmedse/driver.js). They have a cool demo, too. You can see it by going to [this page](https://kamranahmed.info/driver) and clicking the red buttons at the top.

## Tasks
Here is the current "home page view" of datalab.
![1 - current home page view](https://user-images.githubusercontent.com/13045020/39723061-9674543e-5212-11e8-8bf0-1ff8886de9da.png)

### 1) Remove "Contact" button
![2 - remove contact button](https://user-images.githubusercontent.com/13045020/39723069-9bc39af8-5212-11e8-8bf7-98e20586a17b.png)

### 2) Add a "Guided Tour" button
![3 - add guided help button](https://user-images.githubusercontent.com/13045020/39723084-a72d61f8-5212-11e8-8c25-2c2b16626342.png)

#### 3.1. Start
Welcome to Datalab! You are moments away from visualizing PMA2020 data. Click "next" to get started.
![1 - welcome to datalab you are moments away from visualizing pma2020 data click next to get started](https://user-images.githubusercontent.com/13045020/39825304-7d626706-537f-11e8-8fbe-99f5fc24d32a.png)

#### 3.2. Country Survey-Rounds
PMA2020 datasets are categorized by country and survey round.
![2 - pma datasets are categorized by country and survey round](https://user-images.githubusercontent.com/13045020/39825975-3a22a544-5381-11e8-9a52-23f2c4cca220.png)

#### 3.3. Country Survey-Rounds 2
Here you see all of the countries where PMA2020 collects data. Select a country's name and select from an expanded list of survey rounds for that country.
![3 - here you see all of countries where pma2020 collects data select the country name to expand and then select survey rounds for that country](https://user-images.githubusercontent.com/13045020/39825976-3a2ecea0-5381-11e8-83ef-38e53dd899b1.png)

#### 3.4. Indicators
Next, you probably want to select an indicator!
![4 - next you probably want to select an indicator](https://user-images.githubusercontent.com/13045020/39825977-3a43c698-5381-11e8-9998-10b27d321364.png)

#### 3.5. Characteristics
You may also want to disaggregate the data. To do this, select and open the "break data down by" menu. If options are greyed out, it means that the particular option is not valid for either the indicator or country(s) that you selected.

If you do not wish to disaggregate, select "None".
![5 - next you may want to disaggregate your data select the break data down by menu to show a list of the the data can be disaggregated if options are greyed out that means that they are not valid for either the indicator or country s you select](https://user-images.githubusercontent.com/13045020/39825978-3a50701e-5381-11e8-897a-140f58d5ff0f.png)

#### 3.6. Chart type & over time
Select a chart type.

If you have multiple survey rounds selected, you can also enable the "Over Time" option to see a different way of visualizing the data over time.
![6 - select a chart type if you have multiple survey round sselected you can also turn on the over time option to see a different way of visualizaing the data ove rtime](https://user-images.githubusercontent.com/13045020/39825979-3a61546a-5381-11e8-8f21-e9160aa41826.png)

#### 3.7. Chart button
Now you're ready to chart!
![7 now you re ready to chart](https://user-images.githubusercontent.com/13045020/39825980-3a70c6ca-5381-11e8-9717-1c145c2eb33b.png)

#### 3.8. About the graph 1
After charting, you can hover over bars or lines to see more information.

You can also select different country survey rounds to show or hide them from the chart.
![8 - you now have a graph you can hover over bars or lines to see mor einformation you can also select different country rounds to show hide them](https://user-images.githubusercontent.com/13045020/39825982-3a7f517c-5381-11e8-8f74-1f7f417ef40a.png)

#### 3.9. About the graph 2
You can also select the triple-line (also called "hamburger" icon) to print or save the chart.
![9 - you can also click the triple-line also called hamburger icon to print or save the chart](https://user-images.githubusercontent.com/13045020/39825983-3a8dcc7a-5381-11e8-9877-c47b76aef038.png)

#### 3.10. Definitions
Select the "Definitions" tab to see technical definitions for indicators or disaggregation options.
![10 - click the definitions tab to see technical definitions for indicators or disaggregation options](https://user-images.githubusercontent.com/13045020/39825984-3a9ccc2a-5381-11e8-8fee-50fc0610b96d.png)

#### 3.11. Styles
Select the "Styles" tab for a wealth of options for styling your chart.
![11 click the style tab for a wealth of options to style your chart s](https://user-images.githubusercontent.com/13045020/39825985-3aaf5b24-5381-11e8-90fe-35be6ff8a4d0.png)

#### 3.12. Dataset download
If you want to download a whole dataset, you can do so using the button with the download icon.
![end - if you just want to download a whole dataset you can do so using the button with the download icon](https://user-images.githubusercontent.com/13045020/39825986-3abf67ee-5381-11e8-99a3-e5b6ac3662d0.png)

#### 3.13. Finish
That's it!

We hope you enjoy using datalab. If you ever need anything, you can always reach out to us here.
![end 2 - that s it we hope you enjoy using datalab if you ever need anything you can always reach out to us here - previous - finish](https://user-images.githubusercontent.com/13045020/39825987-3aceb14a-5381-11e8-9cd5-6acda7bd2b8a.png)

## Task List
- [x] 1) Remove "Contact" button
- [x] 2) Add a "Guided Tour" button
- [x] 3) Add the guided tour
- [ ] 4) Finalize with any refactoring / optimization / bugfixes / etc

**Comment by joeflack4** [comment]
@bciar I love it. Looks great on local. When you are finished working on / refactoring / optimizing this, let me know and I will close the issue.

**Comment by joeflack4** [comment]
I love it. I think others will like it too. I will get feedback from them and we will make some text updates I think.
