### ISSUE TITLE
Review and fix vulnerable dependency

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#62]
## Description
GitHub is telling us that we have a vulnerable dependency.

![screen shot 2018-06-20 at 10 27 47 am](https://user-images.githubusercontent.com/13045020/41664905-befcc2a4-7474-11e8-9dd8-0e4bf0567fe3.png)

## Tasks
- [x] Locate vulnerable dependency(ies)
- [x] Recommend a course of action to Joe
- [x] Wait for response
- [x] Install / uninstall / upgrade / downgrade dependency(ies) after response

**Comment by joeflack4** [comment]
Updated from package.json and package.lock.json from bciar branch into master, pushed, and this warning message disappeared. Issue looks solved. @bciar Thanks!
