### ISSUE TITLE
Testing: Checking for charts to render correctly

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#74]
## Description
~This is going to be a big one. Basically, I would like to add automated tests for most/all of the bugs that we have fixed in [version 1.2.0](https://github.com/PMA-2020/datalab/releases/tag/1.2.0).~

~Personally, I don't know much about how to do this. @bciar Let's please have a discussion on Slack soon when you have time!~

After talking about this, I think we should only do 1 type of test for this issue: download image and check that it matches what we expect.

Here are the steps,
1. We have a pre-downloaded png files, with query parameters as the file name. _For example, surveyCountries=PMA2014_BFR1,PMA2015_BFR2&indicators=cp_all&characteristicGroups=age_5yr_int&chartType=bar&overTime=false.png_
2. We run a test that goes to the URL with query parameters matching the file name. _For example, http://localhost:4567/?surveyCountries=PMA2014_BFR1,PMA2015_BFR2&indicators=cp_all&characteristicGroups=age_5yr_int&chartType=bar&overTime=false_
3. The test then downloads the image. _For example, see attachment 1._
4. The test then runs md5 and checks that the hash of the pre-downloaded png matches the hash of the newly downloaded png. _For example, `1e1ec4fd013b251ea3581bc9bca65eb6`_

## Tasks
- [x] 1. Choose a test framework
- [x] 2. Save test-related dependencies in package.json
- [ ] 3. Add "test" script to package.json
- [x] 4. Make test(s) for all of the images in _attachment 2._
- [x] 5. Make test(s) for all of the images in _attachment 3._
- [x] 6. Make test(s) for all of the images in _attachment 4._
- [x] 7. Make test(s) for all of the images in _attachment 5._ *(note: these have styles, so this will be harder)*

---
**Attachments**
1. 
[surveyCountries=PMA2014_BFR1,PMA2015_BFR2&indicators=cp_all&characteristicGroups=age_5yr_int&chartType=bar&overTime=false.png](https://user-images.githubusercontent.com/13045020/42398361-94222fb8-8137-11e8-8377-e8b498e87348.png)
2. [pre-downloaded images (no styles, no over-time, no pie charts)](https://github.com/PMA-2020/datalab/files/2171941/imageMatchingTests.zip)
3. [pre-downloaded images (no styles, no over-time, pie charts)](https://github.com/PMA-2020/datalab/files/2176997/imageMatchingTests2_noStyles_noOverTime_pie.zip)
4. [pre-downloaded images (no styles, over-time)](https://github.com/PMA-2020/datalab/files/2176998/imageMatchingTests3_noStyles_overTime.zip)
5. [pre-downloaded images (styles)](https://github.com/PMA-2020/datalab/files/2177000/imageMatchingTests4_styles.zip)
