### ISSUE TITLE
Text updates: Guided tour

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#83]
## Description
Update some text in the guided tour.

## Tasks
- [ ] 1. About the graph 1 --> About charts
- [ ] ~~2. About the graph 2 --> About charts~~
- [ ] 3. That's it! We hope you enjoy using datalab. If you ever need anything, you can always reach out to us here. --> That's it! We hope you enjoy using **Datalab**. If you ever need anything, you can always reach out to us here.

---
**Screenshots**

![about charts 1](https://user-images.githubusercontent.com/13045020/42236416-cc0db670-7ec8-11e8-903c-021530635cde.png)

**Comment by joeflack4** [comment]
@bciar Thanks! Actually, edit (2) was an error; I forgot that in issue #70, this text had already been changed. But I checked your changes, and they are perfect, thanks.
