### ISSUE TITLE
Add linter to package.json

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#84]
## Description
To prevent an issue where different developers are using different linters or linter versions, we want to add the linter as a dependency.

## Tasks
- [x] 1. Add linter to dev dependencies.
- [x]  2. Commit the linter configuration file to the project. (oh... I see there is already an .eslint.js -- is this yours?)
- [x] 3. Add the following script to package.json: `./node_modules/.bin/eslint .`

**Comment by bciar** [comment]
### **Answer**
I added a "eslint 5.0.1" in the devDependencies.
https://eslint.org/docs/user-guide/getting-started
As you can see here, if you install the eslint for only project not globally, you need to run 
$ ./node_modules/.bin/eslint yourfile.js
If this is complicated and inconvenient, you can install the eslint globally by
$ npm install -g eslint
and simply can run 
eslint yourfile.js
Thanks.

**Comment by joeflack4** [comment]
@bciar Hey Bciar. Thank you. I created a test branch and installed locally using these steps:

> 1. If you want to include ESLint as...
> `$ npm install eslint --save-dev`
I skipped this step (I have it installed globally).

> 2. You should then setup a configuration file:
> `$ ./node_modules/.bin/eslint --init`
When I ran this command, it asked me some questions. I selected "JSON" for my config format and it produced a file `.eslintrc.json`.

> 3. After that, you can run ESLint in your project’s root directory like this:
> `$ ./node_modules/.bin/eslint yourfile.js`
I ran the command `./node_modules/.bin/eslint .`. It produced many lint errors. However, this is because I am not using your configuration. I selected my configuration randomly in step (2).

*What I think we should do next*
I trust your choices for linting. Can you choose one of two options: (a) add your global `.eslintrc` file to the project, or (b) after adding to dev dependencies (you already did this), create the `.eslintrc` file by running the setup in step (2).

At PMA2020 we prefer for all developers to use the same lint configuration in the same project.

**Comment by joeflack4** [comment]
@bciar After working on this together, this looks good now!
